# Generated by Django 3.2.7 on 2021-11-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('user', '사용자')], max_length=10, verbose_name='등급')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
